name: DAST Scan
on:
  schedule: 
  - cron: '45 3 * * 4'
  workflow_dispatch:

jobs:
  zap_baseline_scan:
    runs-on: ubuntu-latest
    name: Scan the application
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'http://ec2-52-34-47-41.us-west-2.compute.amazonaws.com'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: ''
