name: Security Tests CI

on: 
  #push:
  #  branches: [aws-deployment]
  pull_request:
    branches: [aws-deployment]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set Up Python 
        uses: actions/setup-python@v2
        with:
          python-version: "3.12.3"
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        env:
          DEBUG: ${{ secrets.DEBUG }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          # DB_NAME: ${{ secrets.DB_NAME }}
        run: |
        #  python manage.py test
          