name: Security Tests CI

on: 
  push:
    branches: [aws-deployment]
  pull_request:
    branches: [aws-deployment]

jobs:
  test:
    runs-on: ubuntu-22.04
    # strategy:
    #  max-parallel: 4
    #  matrix:
    #    python-version: [3.12.3]

    steps:
      - uses: actions/checkout@v2
      #- name: local act python setup fix
        #run: |
          # Hack to get setup-python to work on act
          # (see https://github.com/nektos/act/issues/251)
          #if [ ! -f "/etc/lsb-release" ] ; then
          #  echo "DISTRIB_RELEASE=22.04" > /etc/lsb-release
          #fi
          #apt update
          #apt install glibc-source -y
      - name: Set Up Python 
        uses: actions/setup-python@v2
        with:
          python-version: "3.12.3"
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        env:
          DEBUG: ${{ secrets.DEBUG }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          # DB_NAME: ${{ secrets.DB_NAME }}
        run: |
          python manage.py test core.tests
          